### PR TITLE
um7: initial debianization (#1198)

### PR DESCRIPTION
**Pull request by dankamongmen**
Debianize um7 for use on ubuntu bionic (#2

### CODE REVIEW

**Comment by dankamongmen** [comment]
@Spwizzard  get in here

**Comment by Spwizzard** [comment]
Sorry about that, will be adding you now.

**Comment by dankamongmen** [comment]
Cool, I'll go ahead and build the binary deb and put it up. I don't think you need to build it in circleci every go through, but you're of course welcome to.

**Comment by dankamongmen** [comment]
```
[greenziehq](254) $ sudo reprepro -b /usr/local/var/lib/reprepro/  ls ros-melodic-um7
ros-melodic-um7 |                 0.0.4-bionic1 |               bionic | amd64
ros-melodic-um7 | 0.0.4-0bionic.20190601.020649 |           bionic-ros | amd64
ros-melodic-um7 | 0.0.4-0bionic.20190601.020649 | bionic-ubuntu-update | amd64
[greenziehq](0) $ 
```

**Pull request merged**
